### ISSUE TITLE
ضرورى جدا

### ISSUE THREAD

**Issue by kreem1986** [kreem1986/SmartHealthAI#2]
سددت رسوم الدورة وانهيت التدريب لكن توقفت عند مرحلة انشاء الموضوع لحصول على الشهادة
ارجو المساعدة الضرورىة
![Screenshot (1)](https://github.com/kreem1986/SmartHealthAI/assets/140700760/daf5aab3-5a98-44a4-b553-95c7e6346b5a)

![Screenshot (2)](https://github.com/kreem1986/SmartHealthAI/assets/140700760/a05701b7-658a-4228-afd1-a817d5b30c76)

Couldn't fetch your README. Please make sure you entered the correct URL to your GitHub repository.

**Comment by 247TaxiDriver** [comment]
السلام عليكم اخي كريم
كيف الحال؟
ممكن تساعدني في توثيق العملات وختمها ومن بعد ذالك نعمل الها revoke من العملات المستودعه في عدة منصات تداول ومنصات تخزين وغيرها 
خدعوني لمده ٤ سنوات واخفوا عني الملايين بل البلايين من الدولورات وسوف اقوم بدفع نسبة ١٠٪؜ لك بعد النجاح من ختم العملات وتوثيقها واصلاح الكودينق لانهم اخترقوا كل شي يخصني وقاموا بتغيير عدة اوامر 
انا اعمل على ذالك من مدة ٣ اشهر ليل ونهار وبدون جدوه استرجاع 
ادخل لحساب التويتر عندي وسوف ترى منشوراتي وكيف تم خداعي من بينانس وغيرها. تويتر Taxi247Driver
